### ISSUE TITLE
Using of discard probabilities

### ISSUE THREAD

**Issue by zetyquickly** [theeluwin/pytorch-sgns#4]
As I can see the 'ws' variable representing discard probabilities of each word is unused. Should it be applied for calculating weights?

**Comment by zetyquickly** [comment]
Ok. I find out that it can be used in the init method of dataloader class

**Comment by theeluwin** [comment]
Yep. Calculated from https://github.com/theeluwin/pytorch-sgns/blob/master/train.py#L57 and used in https://github.com/theeluwin/pytorch-sgns/blob/master/train.py#L36
It's a subsampling method from https://arxiv.org/pdf/1310.4546.pdf section 2.3.
![2018-06-25 02 53 00](https://user-images.githubusercontent.com/1303549/41821932-ee9e6b78-7822-11e8-82c2-53c4ccc424c1.png)
